// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/onnoink/gin-seed-layout/internal/biz"
	"github.com/onnoink/gin-seed-layout/internal/data"
	"github.com/onnoink/gin-seed-layout/internal/server"
	"github.com/onnoink/gin-seed-layout/internal/service"
)

// Injectors from wire.go:

func wireGin() *gin.Engine {
	helloRepo := data.NewHelloRepo()
	helloUseCase := biz.NewPassportUseCase(helloRepo)
	serviceService := service.NewService(helloUseCase)
	engine := server.NewServer(serviceService)
	return engine
}
